services:
  master:
    build: { context: ., dockerfile: Dockerfile.cluster }
    container_name: rpic_master
    hostname: master
    mem_limit: 1g
    cpus: 2.0
    ports: ["2222:22"]
    volumes:
      - ./workspace:/home/pi/workspace
  
  worker1:
    build: { context: ., dockerfile: Dockerfile.cluster }
    container_name: rpic_worker1
    hostname: worker1
    mem_limit: 1g
    cpus: 2.0
    ports: ["2223:22"]
    volumes:
      - ./workspace:/home/pi/workspace
    profiles: ["worker1", "2-nodes", "3-nodes", "4-nodes", "5-nodes", "6-nodes"]
  
  worker2:
    build: { context: ., dockerfile: Dockerfile.cluster }
    container_name: rpic_worker2
    hostname: worker2
    mem_limit: 1g
    cpus: 2.0
    ports: ["2224:22"]
    volumes:
      - ./workspace:/home/pi/workspace
    profiles: ["worker2", "3-nodes", "4-nodes", "5-nodes", "6-nodes"]
  
  worker3:
    build: { context: ., dockerfile: Dockerfile.cluster }
    container_name: rpic_worker3
    hostname: worker3
    mem_limit: 1g
    cpus: 2.0
    ports: ["2225:22"]
    volumes:
      - ./workspace:/home/pi/workspace
    profiles: ["worker3", "4-nodes", "5-nodes", "6-nodes"]
  
  worker4:
    build: { context: ., dockerfile: Dockerfile.cluster }
    container_name: rpic_worker4
    hostname: worker4
    mem_limit: 1g
    cpus: 2.0
    ports: ["2226:22"]
    volumes:
      - ./workspace:/home/pi/workspace
    profiles: ["worker4", "5-nodes", "6-nodes"]
  
  worker5:
    build: { context: ., dockerfile: Dockerfile.cluster }
    container_name: rpic_worker5
    hostname: worker5
    mem_limit: 1g
    cpus: 2.0
    ports: ["2227:22"]
    volumes:
      - ./workspace:/home/pi/workspace
    profiles: ["worker5", "6-nodes"]

networks:
  default:
    driver: bridge
