FROM debian:bullseye-slim
RUN apt-get update && apt-get install -y \
    openssh-server openssh-client openmpi-bin libopenmpi-dev \
    python3 python3-pip python3-numpy sudo time \
    && rm -rf /var/lib/apt/lists/*
RUN pip3 install mpi4py
RUN useradd -m -s /bin/bash pi && echo 'pi:raspberry' | chpasswd && \
    echo 'pi ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
RUN mkdir /var/run/sshd
RUN mkdir -p /home/pi/.ssh && chmod 700 /home/pi/.ssh && \
    ssh-keygen -t rsa -f /home/pi/.ssh/id_rsa -N "" && \
    cat /home/pi/.ssh/id_rsa.pub > /home/pi/.ssh/authorized_keys && \
    chmod 600 /home/pi/.ssh/authorized_keys && \
    echo "Host *" > /home/pi/.ssh/config && \
    echo "  StrictHostKeyChecking no" >> /home/pi/.ssh/config && \
    chmod 600 /home/pi/.ssh/config && \
    chown -R pi:pi /home/pi/.ssh
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
