import matplotlib.pyplot as plt
import numpy as np
import re
import os
from PIL import Image

def parse_log(filepath):
    results = {}
    current_img = None
    
    with open(filepath, 'r') as f:
        for line in f:
            if line.startswith("IMAGE:"):
                current_img = line.split("IMAGE:")[1].strip().split('/')[-1]
                results[current_img] = {'omp': [], 'mpi': [], 'baselines': {}}
            
            # Parse Baseline times
            if "Sobel time:" in line:
                results[current_img]['baselines']['Sobel'] = float(re.search(r"Sobel time: ([\d\.]+)", line).group(1))
            if "FFT Edge time:" in line:
                results[current_img]['baselines']['FFT_Edge'] = float(re.search(r"FFT Edge time: ([\d\.]+)", line).group(1))
                
            # Parse Arch 1 (OpenMP)
            if "FFT Arch1 (Farm) Time:" in line:
                match = re.search(r"FFT Arch1 \(Farm\) Time: ([\d\.]+) s using (\d+) threads", line)
                if match:
                    time = float(match.group(1))
                    threads = int(match.group(2))
                    results[current_img]['omp'].append((threads, time))
                
            # Parse Arch 3 (MPI)
            if "FFT Arch3 (Dist Dynamic/Scatter-Gather) Time:" in line:
                time = float(re.search(r"FFT Arch3 \(Dist Dynamic/Scatter-Gather\) Time: ([\d\.]+)", line).group(1))
                # For this script we assume NODE_COUNTS=(2 4 6)
                nodes = [2, 4, 6][len(results[current_img]['mpi'])]
                results[current_img]['mpi'].append((nodes, time))

    return results

def plot_laws(results, img_name):
    data = results[img_name]
    if not data['mpi']: return
    
    nodes = np.array([x[0] for x in data['mpi']])
    times = np.array([x[1] for x in data['mpi']])
    
    # Speedup
    t1 = data['baselines'].get('FFT_Edge', times[0]*nodes[0]) # Use serial baseline or estimate
    speedup = t1 / times
    efficiency = speedup / nodes
    
    plt.figure(figsize=(12, 4))
    
    # Amdahl's Law Plot
    plt.subplot(1, 3, 1)
    plt.plot(nodes, speedup, 'o-', label='Empirical')
    # Extrapolation
    p_ext = np.linspace(1, 16, 100)
    f = 0.9 # assumed parallel fraction
    s_amdahl = 1 / ((1-f) + f/p_ext)
    plt.plot(p_ext, s_amdahl, '--', label=f'Amdahl (f={f})')
    plt.title("Speedup (Amdahl's Law)")
    plt.xlabel("Nodes")
    plt.ylabel("Speedup")
    plt.legend()
    
    # Efficiency (Isoefficiency context)
    plt.subplot(1, 3, 2)
    plt.plot(nodes, efficiency, 'o-')
    plt.title("Efficiency")
    plt.xlabel("Nodes")
    plt.ylabel("E")
    
    # Brent's Law (Time vs 1/p)
    plt.subplot(1, 3, 3)
    plt.plot(1/nodes, times, 'o-', label='Empirical')
    plt.title("Brent's Law (T vs 1/p)")
    plt.xlabel("1/p")
    plt.ylabel("Time (s)")
    
    plt.tight_layout()
    plt.savefig(f"metrics_{img_name}.png")
    plt.close()

def create_visual_check():
    # Load images generated by the run
    # Expected names: original_gray.png, sobel_out.png, fft_edge_out.png, fft_arch1_out.png ...
    img_files = [
        "workspace/original_gray.png",
        "workspace/sobel_out.png",
        "workspace/fft_edge_out.png",
        "workspace/fft_arch1_out.png",
        "workspace/fft_arch2_out.png",
        "workspace/fft_arch3_out.png",
        "workspace/fft_arch4_out.png"
    ]
    
    titles = ["Original", "Sobel", "FFT Base", "Arch1", "Arch2", "Arch3", "Arch4"]
    
    valid_imgs = []
    for f in img_files:
        if os.path.exists(f):
            valid_imgs.append(Image.open(f))
        else:
            valid_imgs.append(None)
            
    fig, axes = plt.subplots(1, len(valid_imgs), figsize=(20, 5))
    for i, img in enumerate(valid_imgs):
        if img:
            axes[i].imshow(img, cmap='gray')
            axes[i].set_title(titles[i])
        axes[i].axis('off')
        
    plt.savefig("visual_comparison.png")
    plt.close()

if __name__ == "__main__":
    if os.path.exists("analysis_results.log"):
        res = parse_log("analysis_results.log")
        for img in res:
            print(f"Generating plots for {img}...")
            plot_laws(res, img)
        create_visual_check()
        print("Report generation complete: visual_comparison.png and metrics_*.png created.")
    else:
        print("Log file not found. Run ./run_analysis.sh first.")
