#!/usr/bin/env bash
# =============================================================================
# gen_config.sh — Auto-generate rpi/config.env from .local mDNS hostnames
# =============================================================================
# Resolves each Pi's hostname via avahi/getent/ping and writes config.env.
# Run this ONCE before setup_cluster.sh (or whenever IPs change).
#
# Usage:
#   bash rpi/gen_config.sh
# =============================================================================

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="${SCRIPT_DIR}/config.env"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYAN}[gen_config]${NC} $*"; }
success() { echo -e "${GREEN}[gen_config] ✓${NC} $*"; }
warn()    { echo -e "${YELLOW}[gen_config] ⚠${NC} $*"; }
die()     { echo -e "${RED}[gen_config] ✗${NC} $*" >&2; exit 1; }

# ── Resolve a .local hostname to an IP ───────────────────────────────────────
resolve_ip() {
    local host="${1}.local"
    local ip=""

    # Try avahi-resolve (most reliable on Linux)
    if command -v avahi-resolve &>/dev/null; then
        ip=$(avahi-resolve -4 -n "$host" 2>/dev/null | awk '{print $2}')
    fi

    # Fallback: getent hosts
    if [[ -z "$ip" ]]; then
        ip=$(getent hosts "$host" 2>/dev/null | awk '{print $1}')
    fi

    # Fallback: ping
    if [[ -z "$ip" ]]; then
        ip=$(ping -c1 -W2 "$host" 2>/dev/null \
            | grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b' \
            | head -1)
    fi

    echo "$ip"
}

# ── Node definitions ──────────────────────────────────────────────────────────
NODES=(rpi-master rpi-worker1 rpi-worker2 rpi-worker3 rpi-worker4 rpi-worker5)
declare -A RESOLVED

echo ""
echo "════════════════════════════════════════════════════════"
echo "  Resolving Pi hostnames via mDNS (.local)"
echo "════════════════════════════════════════════════════════"

for node in "${NODES[@]}"; do
    info "Resolving ${node}.local ..."
    ip=$(resolve_ip "$node")
    if [[ -n "$ip" ]]; then
        success "${node}.local → ${ip}"
        RESOLVED[$node]="$ip"
    else
        warn "Could not auto-resolve ${node}.local"
        read -rp "  Enter IP for ${node} manually (or leave blank to skip): " ip
        RESOLVED[$node]="${ip:-__FILL_IN__}"
    fi
done

echo ""

# ── Write config.env ──────────────────────────────────────────────────────────
cat > "$OUT" << EOF
# =============================================================================
# RPI Cluster — Auto-generated by gen_config.sh on $(date)
# Edit manually only if IPs change. Re-run gen_config.sh to regenerate.
# This file is gitignored and never committed.
# =============================================================================

# ── Master node ───────────────────────────────────────────────────────────────
MASTER_USER=rpi-master
MASTER_HOST=rpi-master.local
MASTER_IP=${RESOLVED[rpi-master]}

# ── Worker nodes ──────────────────────────────────────────────────────────────
WORKER1_USER=rpi-worker1
WORKER1_HOST=rpi-worker1.local
WORKER1_IP=${RESOLVED[rpi-worker1]}

WORKER2_USER=rpi-worker2
WORKER2_HOST=rpi-worker2.local
WORKER2_IP=${RESOLVED[rpi-worker2]}

WORKER3_USER=rpi-worker3
WORKER3_HOST=rpi-worker3.local
WORKER3_IP=${RESOLVED[rpi-worker3]}

WORKER4_USER=rpi-worker4
WORKER4_HOST=rpi-worker4.local
WORKER4_IP=${RESOLVED[rpi-worker4]}

WORKER5_USER=rpi-worker5
WORKER5_HOST=rpi-worker5.local
WORKER5_IP=${RESOLVED[rpi-worker5]}

# ── Paths ─────────────────────────────────────────────────────────────────────
# Workspace location on every Pi node (Desktop/rpi-vision-cluster/workspace)
RPI_WS_PARENT=~/Desktop/rpi-vision-cluster
RPI_WORKSPACE_DIR=~/Desktop/rpi-vision-cluster/workspace

# Where the game binary lives on all nodes
RPI_GAME_BIN=/tmp/game
EOF

success "Written: ${OUT}"
echo ""

# ── Warn about any unresolved entries ─────────────────────────────────────────
if grep -q "__FILL_IN__" "$OUT"; then
    warn "Some IPs were not resolved. Edit ${OUT} and fill in the remaining __FILL_IN__ values."
else
    success "All IPs resolved. You can now run: bash rpi/setup_cluster.sh"
fi
echo ""
