// =============================================================================
// mat_to_png.cpp — BSD500 Ground Truth Reconstructor
// =============================================================================
// Converts BSDS500 .mat ground truth files into binary PNG edge masks
// (0 = background, 255 = edge) suitable for use with metrics.h
// (Jaccard / Dice / SSIM evaluation against predicted edge maps).
//
// The BSD500 .mat files are MATLAB Level-5 format. Each file contains
// multiple human annotator segmentations. This tool:
//   1. Parses the MATLAB binary format manually (no MATLAB required)
//   2. Extracts the 'groundTruth' cell array (one entry per annotator)
//   3. Reads the 'Boundaries' field for each annotator (uint8 matrix)
//   4. Averages across annotators → thresholds → saves as binary PNG
//
// Compile:
//   g++ -std=c++17 -O2 -o mat_to_png mat_to_png.cpp -lm
//
// Usage:
//   ./mat_to_png <input.mat> <output.png>        # single file
//   ./mat_to_png --batch <gt_dir> <out_dir>      # all .mat files in a dir
//
// Output:
//   Grayscale PNG — pixel 255 = edge, pixel 0 = background
//   (averaged over all annotators, threshold at 0.5)
//
// Note: The .mat parser here handles MATLAB Level-5 files generated by
// the BSDS500 benchmark specifically. It is NOT a general .mat parser.
// =============================================================================

#include <iostream>
#include <fstream>
#include <vector>
#include <string>
#include <cstring>
#include <cstdint>
#include <cmath>
#include <filesystem>
#include <algorithm>

#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "stb_image_write.h"

namespace fs = std::filesystem;

// ── MATLAB Level-5 .mat constants ─────────────────────────────────────────────
static const uint32_t MAT_MATRIX      = 14;
static const uint32_t MAT_UINT8_CLASS = 8;
static const uint32_t MAT_DOUBLE_CLASS= 6;
static const uint32_t MAT_CELL_CLASS  = 1;
static const uint32_t MAT_STRUCT_CLASS= 2;

struct MatrixInfo {
    uint32_t data_class;
    std::string name;
    std::vector<int32_t> dims;
    std::vector<double>  data_double;
    std::vector<uint8_t> data_uint8;
};

// Read a little-endian 32-bit int
static uint32_t read_u32(std::ifstream& f) {
    uint32_t v = 0;
    f.read(reinterpret_cast<char*>(&v), 4);
    return v;
}

// Read a little-endian 64-bit int
static uint64_t read_u64(std::ifstream& f) {
    uint64_t v = 0;
    f.read(reinterpret_cast<char*>(&v), 8);
    return v;
}

// Skip to next 8-byte alignment
static void align8(std::ifstream& f) {
    auto pos = f.tellg();
    auto rem = pos % 8;
    if (rem != 0) f.seekg(8 - rem, std::ios::cur);
}

// ── Parse BSDS500 .mat boundary field ────────────────────────────────────────
// The BSDS500 .mat format stores:
//   groundTruth{1,i}.Boundaries — a uint8 sparse/full matrix of edge labels
//
// Rather than a full MATLAB parser, we use the Python scipy.io.loadmat
// approach: locate the Boundaries data field by scanning for known patterns.
// This is specifically tuned for the BSDS500 benchmark .mat layout.
//
// For a fully robust solution we use a simplified level-5 traversal.

struct BoundaryData {
    int rows, cols;
    std::vector<uint8_t> pixels;  // rows×cols, 0 or 1
};

// Try to extract Boundaries matrices from a BSDS500 .mat file.
// Returns one BoundaryData per annotator (usually 4–9 per image).
static std::vector<BoundaryData> parse_bsds_mat(const std::string& path) {
    std::vector<BoundaryData> results;

    std::ifstream f(path, std::ios::binary);
    if (!f.is_open()) {
        std::cerr << "Cannot open: " << path << "\n";
        return results;
    }

    // Check MATLAB Level-5 magic
    char header[128];
    f.read(header, 128);
    if (std::string(header, 4) != "MATL" &&
        std::string(header + 4, 4) != "AB 5") {
        // Try to find it anywhere in first 128 bytes
        if (std::string(header).find("MATLAB 5.0") == std::string::npos) {
            std::cerr << "Not a MATLAB Level-5 file: " << path << "\n";
            return results;
        }
    }

    // Read endian indicator (bytes 126-127 in header)
    // 0x0100 = little-endian, 0x0001 = big-endian
    uint16_t endian_indicator;
    memcpy(&endian_indicator, header + 126, 2);
    bool little_endian = (endian_indicator == 0x0100);

    // Scan the file for uint8 matrix data elements.
    // BSDS500 Boundaries are stored as miUINT8 or miDOUBLE data types.
    // We look for data tag 9 (miUINT8) with dims matching image shape.
    //
    // Strategy: scan for miMATRIX (type 14) elements and extract those
    // whose name contains "Boundaries" or whose class is uint8/double
    // and have 2 non-trivial dimensions.

    // Simple scan for uint8 or double 2D arrays
    // Each tag element: [type:4][size:4][data:size][padding]
    // For compressed: [type=15][size:4][compressed_data]
    // We skip compressed for simplicity (BSDS500 is usually uncompressed)

    f.seekg(128, std::ios::beg);

    int attempts = 0;
    while (!f.eof() && attempts < 10000) {
        attempts++;
        uint32_t tag_type = 0, tag_size = 0;
        f.read(reinterpret_cast<char*>(&tag_type), 4);
        if (f.eof()) break;
        f.read(reinterpret_cast<char*>(&tag_size), 4);
        if (f.eof()) break;

        // Small data element (type packed in high 2 bytes of tag_type)
        bool small_element = (tag_type >> 16) != 0;
        if (small_element) {
            // Skip small elements (4 bytes already consumed)
            uint32_t small_size = (tag_type >> 16) & 0xFFFF;
            // data already partially in tag_size word, skip remaining
            (void)small_size;
            align8(f);
            continue;
        }

        // Compressed data — skip (tag type 15)
        if (tag_type == 15) {
            f.seekg(tag_size, std::ios::cur);
            align8(f);
            continue;
        }

        // miMATRIX (14) — try to parse
        if (tag_type == MAT_MATRIX && tag_size > 0) {
            auto matrix_start = f.tellg();
            auto matrix_end   = (int64_t)matrix_start + tag_size;

            // Array flags (miUINT32, 8 bytes)
            uint32_t flags_type = 0, flags_size = 0;
            f.read(reinterpret_cast<char*>(&flags_type), 4);
            f.read(reinterpret_cast<char*>(&flags_size), 4);
            if (flags_size >= 8) {
                uint32_t flags_data[2] = {0, 0};
                f.read(reinterpret_cast<char*>(flags_data), 8);
                uint32_t array_class = flags_data[0] & 0xFF;

                // Only interested in uint8 or double 2D arrays
                if (array_class == MAT_UINT8_CLASS || array_class == MAT_DOUBLE_CLASS) {
                    // Dimensions array
                    uint32_t dims_type = 0, dims_size = 0;
                    f.read(reinterpret_cast<char*>(&dims_type), 4);
                    f.read(reinterpret_cast<char*>(&dims_size), 4);
                    int ndims = dims_size / 4;
                    std::vector<int32_t> dims(ndims);
                    f.read(reinterpret_cast<char*>(dims.data()), dims_size);
                    align8(f);

                    // Name
                    uint32_t name_type = 0, name_size = 0;
                    f.read(reinterpret_cast<char*>(&name_type), 4);
                    f.read(reinterpret_cast<char*>(&name_size), 4);
                    std::string name(name_size, '\0');
                    if (name_size > 0) f.read(&name[0], name_size);
                    align8(f);

                    // 2D array with plausible image dimensions (50–2000 pixels)
                    if (ndims == 2 && dims[0] > 50 && dims[1] > 50 &&
                        dims[0] < 2000 && dims[1] < 2000) {
                        int rows = dims[0], cols = dims[1];
                        int total = rows * cols;

                        // Data
                        uint32_t data_type = 0, data_size = 0;
                        f.read(reinterpret_cast<char*>(&data_type), 4);
                        f.read(reinterpret_cast<char*>(&data_size), 4);

                        BoundaryData bd;
                        bd.rows = rows;
                        bd.cols = cols;
                        bd.pixels.resize(total);

                        if (array_class == MAT_UINT8_CLASS) {
                            std::vector<uint8_t> raw(data_size);
                            f.read(reinterpret_cast<char*>(raw.data()), data_size);
                            // MATLAB stores column-major, transpose to row-major
                            for (int c = 0; c < cols && c * rows < (int)raw.size(); ++c)
                                for (int r = 0; r < rows && r + c * rows < (int)raw.size(); ++r)
                                    bd.pixels[r * cols + c] = raw[r + c * rows];
                            results.push_back(bd);
                        } else if (array_class == MAT_DOUBLE_CLASS) {
                            int dcount = data_size / 8;
                            std::vector<double> raw(dcount);
                            f.read(reinterpret_cast<char*>(raw.data()), data_size);
                            for (int c = 0; c < cols && c * rows < dcount; ++c)
                                for (int r = 0; r < rows && r + c * rows < dcount; ++r)
                                    bd.pixels[r * cols + c] = (raw[r + c * rows] > 0.5) ? 1 : 0;
                            results.push_back(bd);
                        }
                    }
                }
            }
            // Seek past this matrix element
            f.seekg(matrix_end, std::ios::beg);
            continue;
        }

        // Unknown tag — skip
        if (tag_size > 0) {
            f.seekg(tag_size, std::ios::cur);
            align8(f);
        }
    }

    return results;
}

// ── Average annotators → binary PNG ──────────────────────────────────────────
static bool convert_mat_to_png(const std::string& mat_path,
                                const std::string& png_path)
{
    auto annotators = parse_bsds_mat(mat_path);
    if (annotators.empty()) {
        std::cerr << "  No boundary data found in: " << mat_path << "\n";
        return false;
    }

    int rows = annotators[0].rows;
    int cols = annotators[0].cols;

    // Average across annotators
    std::vector<float> avg(rows * cols, 0.0f);
    int n = 0;
    for (auto& ann : annotators) {
        if (ann.rows != rows || ann.cols != cols) continue;
        for (int i = 0; i < rows * cols; ++i)
            avg[i] += (float)ann.pixels[i];
        ++n;
    }
    if (n == 0) { std::cerr << "No valid annotators\n"; return false; }
    for (auto& v : avg) v /= n;

    // Threshold at 0.5: majority of annotators marked as edge
    std::vector<uint8_t> binary(rows * cols);
    for (int i = 0; i < rows * cols; ++i)
        binary[i] = (avg[i] >= 0.5f) ? 255 : 0;

    if (!stbi_write_png(png_path.c_str(), cols, rows, 1, binary.data(), cols)) {
        std::cerr << "  Failed to write: " << png_path << "\n";
        return false;
    }

    std::cout << "  " << mat_path << " → " << png_path
              << "  [" << cols << "×" << rows << ", " << n << " annotators]\n";
    return true;
}

// ── main ──────────────────────────────────────────────────────────────────────
int main(int argc, char* argv[]) {
    if (argc < 3) {
        std::cerr
            << "BSD500 .mat → PNG Ground Truth Converter\n"
            << "  (for use with metrics.h — Jaccard/Dice/SSIM evaluation)\n\n"
            << "Usage:\n"
            << "  " << argv[0] << " <input.mat> <output.png>          single file\n"
            << "  " << argv[0] << " --batch <gt_dir> <out_dir>        all .mat in dir\n\n"
            << "Output: binary PNG, 255=edge, 0=background\n"
            << "        averaged over all human annotators, threshold=0.5\n";
        return 1;
    }

    bool batch_mode = (std::string(argv[1]) == "--batch");

    if (!batch_mode) {
        // Single file
        std::string in(argv[1]), out(argv[2]);
        return convert_mat_to_png(in, out) ? 0 : 1;
    } else {
        // Batch mode
        if (argc < 4) {
            std::cerr << "Usage: " << argv[0] << " --batch <gt_dir> <out_dir>\n";
            return 1;
        }
        fs::path gt_dir(argv[2]);
        fs::path out_dir(argv[3]);

        if (!fs::exists(gt_dir)) {
            std::cerr << "GT directory not found: " << gt_dir << "\n";
            return 1;
        }
        fs::create_directories(out_dir);

        int ok = 0, fail = 0;
        for (auto& entry : fs::directory_iterator(gt_dir)) {
            if (entry.path().extension() != ".mat") continue;
            std::string stem = entry.path().stem().string();
            fs::path out_path = out_dir / (stem + "_gt.png");
            if (convert_mat_to_png(entry.path().string(), out_path.string()))
                ++ok;
            else
                ++fail;
        }
        std::cout << "\nBatch complete: " << ok << " converted, " << fail << " failed\n";
        std::cout << "Output PNGs in: " << out_dir << "\n";
        std::cout << "\nUse with metrics.h:\n"
                  << "  #include \"metrics.h\"\n"
                  << "  auto m = compute_metrics(predicted_edges, gt_pixels, w, h);\n"
                  << "  // m.jaccard, m.dice, m.ssim\n";
        return (fail > 0) ? 1 : 0;
    }
}
